config/routes.rb
Rails.application.routes.draw do
  get 'comments/destroy'
 devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   
 } 

 devise_scope :user do
  get "user/:id", :to => "users/registrations#detail"
  get "signup", :to => "users/registrations#new"
  get "login", :to => "users/sessions#new"
  get "logout", :to => "users/sessions#destroy"
 end
 
 
 resources :articles do
  resources :comments, only: [:create, :destroy
  ]
 end
 root to: 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    
    mount_uploader :image, ImageUploader

    belongs_to :user
    has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :sign_in_required
    
    def index
        @articles = Article.order(created_at: :desc).page(params[:page]).per(10)
    end
    
    def show
        @article = Article.find(params[:id])
        @comments = @article.comments
        @comment = Comment.new
        @comment.user_id = current_user.id
        @comment.user_name = current_user.name

    end
    
    def new
        @article= Article.new
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def create
        @article=current_user.articles.build(article_params)
        
         if @article.save
            flash[:success] = '記事 が正常に投稿されました'
            redirect_to @article
         else
            flash.now[:danger] = '記事 が投稿されませんでした'
            render :new
         end
    end
    
    def update
        @article = Article.find(params[:id])
        
        if @article.update(article_params)
            flash[:success] = '記事 は正常に更新されました'
            redirect_to @article
        else
            flash.now[:danger] = '記事 は更新されませんでした'
            render :edit
        end
    end

    def destroy
         @article = Article.find(params[:id])
         @article.destroy
          
        flash[:success] = '記事 は正常に削除されました'
        redirect_to articles_url
        
    end
    
private

def article_params
 params.require(:article).permit(:title ,:body ,:image, :user_id , :article_id)   
end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="form-group">
  <div><%= f.label :title, 'タイトル' %></div>
  <%= f.text_field :title, class:'control-label' %>
  </div>
  
  <div class="form-group">
  <div><%= f.label :body, '本文' %></div>
  <%= f.hidden_field :body, class:'control-label', id: :article_body %>
  <trix-editor input="article_body"></trix-editor>
  </div>

  <div class="form-group">
  <div><%= f.label :image, '画像' %></div>
  <div><%= f.file_field :image %></div>
  </div>
  

  <%= f.submit '投稿', class: 'btn btn-primary'%>
<% end %>
  
  

app/views/articles/edit.html.erb
<h1>編集ページ</h1>

<%= render 'articles/form',article: @article %>

app/views/articles/index.html.erb
ようこそ！　<%= current_user.name %>さん
<h1>
    <div class="text-center">ken's blog</div>
</h1>

<div class="col-sm-2 mx-auto">投稿一覧</div>

<div class="container">
    <div class="row">
        <% @articles.each do |article| %>
            <div class="card col-sm-7 mb-3 mx-auto ">
                <%= link_to article.title,article %>
            </div>
        <% end %>
    </div>
</div>
<div class="col-sm-2 mx-auto"><%= paginate @articles %></div>

app/views/articles/new.html.erb
<h1>新規作成ページ</h1>

<%= render 'articles/form' ,article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %> </h1>
<div class="card border-light bg-white mb-3">
    <%= sanitize @article.body, tags: %w(h1 h2 h3 h4 h5 h6 ul ol li p a img table tr td em br strong div), attributes:  %w(id class href) %>
    <% if @article.image?  %>
        <%= image_tag @article.image.url%>
    <% end %>
</div>
<% if current_user.try(:admin?) %>
<%= link_to '編集', edit_article_path(@article), class:'btn btn-info'%>
<%= link_to '削除', @article, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } , class:'btn btn-danger' %>
<% end %>

<h2>コメント一覧</h2>
<% @comments.each do |c| %>
  <div>
    投稿者：<%= c.user_name %>
    内容：<%= c.content %>
    <%= link_to "削除", article_comment_path(article_id: @article.id , id: c.id), method: :delete %>
  </div>
<% end %>

<%= form_for [@article, @comment] do |f| %>
  <div class="form-group">
      <%= f.text_field :content, class:'control-label' %>
  </div>
  <%= f.submit 'コメントする', class: "btn btn-primary"  %>
<% end %>